"""Create initial tables

Revision ID: bc5b835ea4ea
Revises: 
Create Date: 2025-02-14 22:08:23.076874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5b835ea4ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_obrigacoes_acessorias_id', table_name='obrigacoes_acessorias')
    op.drop_table('obrigacoes_acessorias')
    op.drop_index('ix_empresas_id', table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('empresas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='empresas_pkey'),
    sa.UniqueConstraint('cnpj', name='empresas_cnpj_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_empresas_id', 'empresas', ['id'], unique=False)
    op.create_table('obrigacoes_acessorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('periodicidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='obrigacoes_acessorias_empresa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='obrigacoes_acessorias_pkey')
    )
    op.create_index('ix_obrigacoes_acessorias_id', 'obrigacoes_acessorias', ['id'], unique=False)
    # ### end Alembic commands ###
